2021-12-29 12:59:49.118 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2092), thread 'MainThread' (139750478002480):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f1a2ef86a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f1a2eb30dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f1a2eb30ee0>
    └ <function Scaffold.run at 0x7f1a2ea49430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f1a2ea49430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7f1a2fb9ac40>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7f1a2ef845e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7f1a2efcaee0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7f1a2efca5e0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7f1a2efca670>
               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7f1a2efca700>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7f1a2efca8b0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7f1a2efc9160>
              └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7f1a2ea47fd0>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 13:06:36.905 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (1951), thread 'MainThread' (140441749584176):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fbb21f7ba60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fbb21b25dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fbb21b25ee0>
    └ <function Scaffold.run at 0x7fbb21a3e430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fbb21a3e430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fbb22b8db20>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fbb21f795e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fbb21fbfee0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fbb21fbf5e0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fbb21fbf670>
               └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fbb21fbf700>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fbb21fbf8b0>
           └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fbb21fbe160>
              └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fbb21a3cd60>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fbb21a3cbe0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 13:12:02.956 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2151), thread 'MainThread' (140484411164976):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fc510cbea60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fc51086adc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fc51086aee0>
    └ <function Scaffold.run at 0x7fc51077f430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fc51077f430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fc5118d2d00>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fc510cbc5e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fc510d01ee0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fc510d015e0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fc510d01670>
               └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fc510d01700>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fc510d018b0>
           └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fc510d00160>
              └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fc51077df70>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fc51077daf0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 14:50:13.292 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (1922), thread 'MainThread' (140662242650416):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fee7860fa60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fee781badc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fee781baee0>
    └ <function Scaffold.run at 0x7fee780d1430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fee780d1430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fee79b46a90>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fee7860d5e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fee78652ee0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fee786525e0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fee78652670>
               └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fee78652700>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fee786528b0>
           └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fee78651160>
              └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fee780cff10>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fee780cfa90>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2021-12-29 14:52:04.393 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2093), thread 'MainThread' (140586310777136):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7fdcca7c7a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7fdcca371dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7fdcca371ee0>
    └ <function Scaffold.run at 0x7fdcca28a430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7fdcca28a430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7fdccbd50fd0>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7fdcca7c55e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7fdcca80bee0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7fdcca80b5e0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7fdcca80b670>
               └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7fdcca80b700>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7fdcca80b8b0>
           └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7fdcca80a160>
              └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7fdcca288f40>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7fdcca288af0>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
2023-12-09 08:42:47.572 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2023-12-09 08:42:47.642 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2023-12-09 21:03:08.723 | ERROR    | __main__:handle_html:66 - Expecting value: line 1 column 1 (char 0)
2025-07-25 09:26:59.641 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 09:26:59.949 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:37:20.854 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 20:37:20.866 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 21:22:39.736 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-25 21:22:39.745 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 09:24:51.702 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 09:24:51.901 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:34:24.666 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 20:34:25.065 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 21:15:59.350 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-26 21:15:59.353 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:43:36.957 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 09:43:36.959 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:35:24.083 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 20:35:24.085 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 21:17:08.700 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-27 21:17:08.702 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 09:42:04.070 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 09:42:04.308 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:39:15.319 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 20:39:15.330 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 21:26:21.209 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-28 21:26:21.211 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:47:30.530 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 09:47:30.647 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:39:40.260 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 20:39:40.262 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 21:27:49.314 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-29 21:27:49.317 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 09:38:30.414 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 09:38:30.416 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:39:21.798 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 20:39:21.807 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 21:27:17.600 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-30 21:27:17.602 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 09:28:28.881 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 09:28:28.883 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:37:16.634 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 20:37:16.636 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 21:24:35.789 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-07-31 21:24:35.791 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:47:30.520 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 09:47:30.525 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 20:38:06.439 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 20:38:06.442 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 21:24:27.338 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-01 21:24:27.767 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-02 09:24:56.418 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-02 09:24:56.988 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-02 20:34:48.794 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-02 20:34:48.796 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-02 21:16:36.553 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-02 21:16:36.556 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-03 09:45:21.064 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
2025-08-03 09:45:21.066 | ERROR    | __main__:handle_html:66 - Expecting value: line 3 column 1 (char 2)
